version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: wines_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: wines_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DB=wines
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: wines_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
