apiVersion: apps/v1
kind: Deployment
metadata:
  name: wines-frontend
  namespace: wines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wines-frontend
  template:
    metadata:
      labels:
        app: wines-frontend
    spec:
      containers:
        - name: frontend
          image: vericachochorovska/wines-frontend:v4
          ports:
            - containerPort: 80
