apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wines-ingress
  namespace: wines
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: wines.local
      http:
        paths:
          # FRONTEND
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wines-frontend
                port:
                  number: 80

          # BACKEND API
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: wines-backend
                port:
                  number: 8000
